### ISSUE TITLE
scripts require upgrade for newly released version 3 of helm

### ISSUE THREAD

**Issue by ericarlier** [kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference#30]
Hey Kai,
Just to let you know that your scripts don't work anymore with the very new helm 3. As I am not an expert in helm and K8's, I don't feel comfortable suggesting changes, but here is what I noticed:
- First aspect is that you don't need to set up tiller anymore.
- there seems also to be some cli disrupting changes, like the --name tag is also no more accepted on the helm install commands

Just to make you aware
Cheers
Eric

**Comment by kaiwaehner** [comment]
Helm 3 is definitely a major change to Kubernetes (no surprise the scripts do not work anymore). 

We should definitely do this upgrade. 

@sbaier1 @ora0600 - Who can do this? (no hurry)

**Comment by kaiwaehner** [comment]
By the way: Confluent Operator won’t officially support helm 3 before release 5.4. We have to wait until 5.4 is out in December anyway... But then it would be great if we can update the demo...

**Comment by kaiwaehner** [comment]
@ericarlier We updated the project in January 2020. It now **uses Helm 3 and does not require Tiller anymore**.
It would be great if you can try out to get it running again. And please create another issue if there are any problems or unclear descriptions.
