### ISSUE TITLE
CRD Hook Doesn't Exist

### ISSUE THREAD

**Issue by rawkode** [kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference#35]
During `terraform apply`

```
null_resource.setup-messaging (local-exec): manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
```

**Comment by sbaier1** [comment]
AFAIK this is just a warning from helm3 to notify about deprecated hooks that were formerly used to install CRDs in helm2 (prometheus-operator chart still has those in place i believe).
Does not break anything though, as helm3 will install the CRDs anyway.
