### ISSUE TITLE
Helm Directory Doesn't Exist

### ISSUE THREAD

**Issue by rawkode** [kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference#36]
During `terraform apply`

```
Download Confluent Operator
Operator is installed...
../confluent/01_installConfluentPlatform.sh: line 42: cd: helm/: No such file or directory
```

**Comment by ora0600** [comment]
The script ../confluent/01_installConfluentPlatform.sh expect that you run terraform from terraform-gcp/. So, please go to hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference/infrastructure/terraform-gcp$  form there run your terraform apply. terraform will call ../confluent/01_installConfluentPlatform.sh and this script will download the Confluent Operator into confluent-operator/ and there is helm/ directory.
Please see https://github.com/kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference/blob/master/infrastructure/confluent/01_installConfluentPlatform.sh beginning with line 20

**Comment by ora0600** [comment]
Sorry, wrong answer. Your Operator is already installed. So, please before executing terraform  delete confluent-operator/ in hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference/infrastructure/terraform-gcp$
So, then the Operator will be installed fresh.
