### ISSUE TITLE
amazing project! - finished example

### ISSUE THREAD

**Issue by andrewczgithub** [kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference#4]
Hi @kaiwaehner 
Love the project!
Was just wondering when i finished example would be ready to run.

Many thanks,
Best,
Andrew

**Comment by kaiwaehner** [comment]
Hi @andrewczgithub ,

we are actively working on this these days and do a first dry-run end to end from MQTT devices to Kafka consumer this week (just in spare time, though). 

It will definitely be ready end of October, as we will present this demo at Confluent Streaming Day in Frankfurt and Zurich early November (+ video recording for Youtube).

**Comment by andrewczgithub** [comment]
fantastic!!
looking forward to it!!
Best,
Andrew
