### ISSUE TITLE
Error from server (NotFound): statefulsets.apps "zookeeper" not found

### ISSUE THREAD

**Issue by mamonteiro-brg** [kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference#43]
Hello,

First of all, thank you very much for the amazing project.

I am trying to deploy the project in GCP and I am having this issue:

> Note: For Openshift Platform replace kubectl commands with 'oc' commands. If OpenShift Route enabled, port will be either 80/443
> After Zookeeper Installation: Check all pods...
> NAME                           READY   STATUS    RESTARTS   AGE
> cc-operator-8498f54f9b-vv4mg   1/1     Running   0          12s
> Error from server (NotFound): statefulsets.apps "zookeeper" not found
> 

I tried to find the instruction that is causing the issue and is this one:
       **15:16 $ kubectl rollout status sts -n operator zookeeper
       **Error from server (NotFound): statefulsets.apps "zookeeper" not found****

Someone have an idea about what's is causing an error like this?

Best Regards,
Manuel Monteiro

**Comment by kaiwaehner** [comment]
Hi Manuel, 

glad that you like the project. 

For the issue, which OpenShift version do you use? 

@sbaier1 @ora0600 What version did we test with? Any idea how to help Manuel?

(Manuel, FYI: We plan to upgrade to new versions of HiveMQ and Confluent Platform soon, this should hopefully also make the getting started easier)

**Comment by mamonteiro-brg** [comment]
Hello Kai Waehner,

Thank you for your reply. I will wait for the new versions, in that way I will check if my error disappears. 

If the new version didn't solve my error I will research what you suggested to me, because I don't see the OpenShift installed in GCP.

Best Regards,
Manuel Monteiro

**Comment by kaiwaehner** [comment]
I synced with @ora0600. The issue is that we run against GCP K8s which is different from Openshift.

The kubectl command only waits until the zookeeper is there. We use a gcp.yaml file. Openshift must use another yaml file. It is best to follow the Openshift documentation (https:/docs.confluent.iocurrentinstallationoperatorco-openshift.html) and translate our project on your own. 

Or just use GCP K8s, for now, to try it out without any changes. If you have it running, it might be easier to "migrate" it to Openshift.

**Comment by mamonteiro-brg** [comment]
Hello Kai Waehner,

Ok, thank you for your help.

If possible, what do I need to implement this second option ? "Or just use GCP K8s, for now, to try it out without any changes. If you have it running, it might be easier to "migrate" it to Openshift."
Do I need to comment some instruction, which one?

I don't see any invocation to the openShift and this is the reason why I ask you that.

Best Regards

**Comment by kaiwaehner** [comment]
You just need an account for GCP. Nothing else. 

Yeah, this is not related to Openshift at all, we just use GKE.

**Comment by mamonteiro-brg** [comment]
Hello  Kai,

Thank you for your time and forget my issue, please don't waste more time with me :).

I will solve the issue and I will come here with the solution.

Best Regards,
Manuel Monteiro

**Comment by ora0600** [comment]
Tomorrow I will update on CP 6.0. And yes Kai is write. We cover only GKE. For openShift you have to use a different yml file. we use the helm/providers/gcp.yaml and you have to use private.yaml for OpenShift.
Please follow this: https://docs.confluent.io/current/installation/operator/co-openshift.html
and then add the our steps from github to install the clusters via OPerator
